version: 3

vars:
  GOALC_BIN_RELEASE_DIR: './build/goalc'
  GK_BIN_RELEASE_DIR: './build/game'
  DECOMP_BIN_RELEASE_DIR: './build/decompiler'
  MEMDUMP_BIN_RELEASE_DIR: './build/tools'
  TYPESEARCH_BIN_RELEASE_DIR: './build/tools'
  OFFLINETEST_BIN_RELEASE_DIR: './build'
  GOALCTEST_BIN_RELEASE_DIR: './build'
  FORMATTER_BIN_RELEASE_DIR: './build/tools'
  EXE_FILE_EXTENSION: ''
  PYTHON: 'python3'
