name: Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: üìù Formatting
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      # sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main'
      # sudo apt install clang-format-15
      # --clang-format-executable $(which clang-format-15)
      - name: Get Package Dependencies
        run: |
          sudo apt update
          sudo apt install clang-format
          clang-format -version

      - name: Check Clang-Formatting
        run: |
          chmod +x ./third-party/run-clang-format/run-clang-format.py
          ./third-party/run-clang-format/run-clang-format.py -r common decompiler game goalc test tools lsp --color always

      - name: Check for Unresolved Conflicts
        run: python ./scripts/gsrc/check-for-conflicts.py
